#!/bin/bash
yum install -y nodejs
mkdir -p /opt/src/nodejs
cd /opt/src/nodejs
wget https://github.com/baltazzard/application/archive/master.zip
unzip -o master.zip
rm -rf master*
cd application-master/
npm install
